### ISSUE TITLE
Add list of killed in Gaza

### ISSUE THREAD

**Issue by julienbrg** [w3hc/palestine#1]
https://data.techforpalestine.org/docs/killed-in-gaza/

**Comment by Julian-Dumitrascu** [comment]
1. I find such work impressive.
How can one learn about your related feelings, views, and goals?
2. For reasons like [one](https://www.theguardian.com/world/2025/aug/06/microsoft-israeli-military-palestinian-phone-calls-cloud) and [two](https://www.bdsmovement.net/microsoft), I don't ask anyone to use Micro software to share that.
We can choose other software.
